name: Build and upload to PyPI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0

      - uses: actions/upload-artifact@v4
        with:
          name: tetgen-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build sdist
        run: pipx run build --sdist

      - name: Install package from sdist
        run: pip install dist/*.tar.gz

      - name: Install test requirements
        run: pip install -r requirements_test.txt

      - name: Run tests
        run: pytest

      - uses: actions/upload-artifact@v4
        with:
          name: tetgen-sdist
          path: dist/*.tar.gz


  release:
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tetgen
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing
      contents: write  # required to create a release
    steps:
      - uses: actions/download-artifact@v4
      - name: Flatten directory structure
        run: |
          mkdir -p dist/
          find . -name '*.whl' -exec mv {} dist/ \;
          find . -name '*.tar.gz' -exec mv {} dist/ \;
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./**/*.whl
